version: "3"
services:
  manage-rkeys:
    container_name: manage-rkeys
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MANAGE_RKEYS_URL: ${MANAGE_RKEYS_URL}

    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - REDIS_URL=${REDIS_URL}
      - REDIS_DATABASE=${REDIS_DATABASE}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - AUTH_LOGIN=${AUTH_LOGIN}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - MANAGE_RKEYS_URL=${MANAGE_RKEYS_URL}
      - LISTEN=:8080
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/ping || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
