version: "3"
services:
  manage-rkeys:
    container_name: manage-rkeys
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - MANAGE_RKEYS_URL=${MANAGE_RKEYS_URL}
      - REDIS_URL=${REDIS_URL}
      - REDIS_DATABASE=${REDIS_DATABASE}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - AUTH_LOGIN=${AUTH_LOGIN}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - LISTEN_SERVER=${LISTEN_SERVER}
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "wget -qO- http://127.0.0.1:8080/ping | grep -q 'pong' || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 3
